### ISSUE TITLE
Allow undo

### ISSUE THREAD

**Issue by Thrillberg** [Thrillberg/imperial#242]
It would be nice if a user has no armies at all yet that if they click maneuver they can undo. Or should we disable maneuver?

**Comment by PedroRCSequeira** [comment]
I dont think it should be disabled, it's a nothing move that sometimes may be used if you know/think your nation will be stolen

That said, I would guess it could just be a misclick, and a confirmation for "are you sure you want to move with no troops?" could be in place

Same for going to investor when the country cant pay everyone (but this one is more likely to be on purpose)

But misclicks can happen in other actions too, I would guess something that would solve all these issues is having a confirmation for you to hit at the end, like a "end turn" thing.

Or just have an undo button that stays there until the next players does an action and then goes away (1 less click :p

**Comment by dmcarmo** [comment]
> Or just have an undo button that stays there until the next players does an action and then goes away (1 less click :p

This reminded me of the Santorini implementation in BGA where, at the end of your turn, you have a timed confirm button. Not sure if it's something worth looking into.

**Comment by PedroRCSequeira** [comment]
It's not just Santorini, I know other games that have it (it may even be a general thing that you can turn on for every game

And yeah it could be a thing, but then I like the "until you opp. makes a move more", it would make live games faster (so you dont have to wait/click somewhere

This "until they make a move" is used, for instance, on "Welcome to" in BGA. Until that happens you have a "restart turn" button
