### ISSUE TITLE
Display a message when attempting to build a factory but all factories are built

### ISSUE THREAD

**Issue by Thrillberg** [Thrillberg/imperial#297]

**Comment by Thrillberg** [comment]
@dmcarmo Just a little hint on this one: You'll probably want to make the change [here](https://github.com/Thrillberg/imperial/blob/c9c3a668c921b5ab04c4a192b3a0380e5df44c40/app/javascript/lib/imperial.js#L1224), which is also where we handle when the nation cannot afford a factory.

**Comment by dmcarmo** [comment]
Actually, after reading the rules and some clarifications (like this one - https://www.boardgamegeek.com/thread/697744/article/7584223#7584223) it looks like we can go to the factory action and do nothing.
As such I think the factory action should not be blocked and, in this specific case, when selecting the factory action it should log a message saying that no more factories can be built and it would just pass to the next player.

**Comment by Thrillberg** [comment]
Ok that sounds good too. I suppose we should do the same for when they cannot afford a factory (but that should be a separate issue on GitHub).

**Comment by Thrillberg** [comment]
I think this can be tackled with #467 if we just allow the factory rondel move but building no factory. That (plus the undo functionality) should be good enough.
