### ISSUE TITLE
Investor action - add tooltip for bonds

### ISSUE THREAD

**Issue by dmcarmo** [Thrillberg/imperial#307]
When purchasing a bond there is already a tooltip for bond trades (red borders) but there's none for straight purchases (green borders).
![image](https://user-images.githubusercontent.com/16320169/108614936-f38a2c80-73f6-11eb-8974-1d4cab0f6ea1.png)

**Comment by Thrillberg** [comment]
Would a tooltip on the green bordered ones be useful? What should it say?

**Comment by dmcarmo** [comment]
My suggestion is to make that screen more uniform, currently some of the bonds have a tooltip and others don't which could be confusing. As for the text, maybe something like `Buy bond`?

Perhaps both bond tooltips could alse have a total cost of the action, like `Buy bond @ 5m` or `Trade in for Germany - 1:2 @ 4m`?
