### ISSUE TITLE
Improve province occupation condition

### ISSUE THREAD

**Issue by dmcarmo** [Thrillberg/imperial#310]
Currently if an army travels to another nation's province it's considered as occupied, but the rules states that in this case the controlling player may declare these armies as `enemy` or `friendly`.
Enemy` armies set a province as occupied and `friendly` armies have no effect on that province's production, factory building, railroad, etc.

**Comment by Thrillberg** [comment]
This will involve a new piece of data to go along with `this.units`. Here is how it is currently structured:
```javascript
Set{
  [Nation]: Set{
    [Province]: {
      armies: 0,
      fleets: 0
    }
  }
}
```
Perhaps we want the inner-most `Object` to actually be:
```javascript
{
  armies: 1,
  fleets: 0,
  friendly: true
}
```
...and we would generally default `friendly` to false.
