### ISSUE TITLE
Swiss bank is given immediatly (it shouldn't

### ISSUE THREAD

**Issue by PedroRCSequeira** [Thrillberg/imperial#319]
Swiss bank card should only be given after the investor action is completed

Right now it is given immediatly, allowing someone who lost their last country to invest during the same action (it could even create a loop I guess, but I didn't test this last part

**Comment by Thrillberg** [comment]
Thanks for submitting this issue, @PedroRCSequeira!! 👋 This is a really valuable rule detail to add. If you want to dig into the code more, I'd be happy to chat further about how it all works. Also, we have a [Slack instance](https://join.slack.com/t/playimperial/shared_invite/zt-ljyq6486-L9~~~ksHdqe23hN71y848w) in case you want to engage there too! Welcome!

**Comment by Thrillberg** [comment]
I think #321 closes this issue! 🎉
