### ISSUE TITLE
Paginate games list

### ISSUE THREAD

**Issue by Thrillberg** [Thrillberg/imperial#326]
We probably want to try to use [Kaminari](https://github.com/kaminari/kaminari). Why don't we go extreme to start and just keep 4 per page? (We have memory bloat issues on production so that is the immediate need for this issue)

**Comment by dmcarmo** [comment]
What do you think of just using Tailwind CSS [components](https://tailwindcomponents.com/search?query=pagination)?

**Comment by Thrillberg** [comment]
These might be helpful, too, but Kaminari will help us by reducing the load from the Rails controller such that the query fetches fewer games. CSS alone won't help with what the server is doing.

On second thought, though, I think this may not be a big priority right now because I'm not sure that it's a query that is causing the issue. I'm still trying to resolve the memory bloat problem.

**Comment by Thrillberg** [comment]
I don't think this is relevant or pressing right now.
