### ISSUE TITLE
Game board

### ISSUE THREAD

**Issue by Thrillberg** [Thrillberg/imperial#56]
@sobelk How do you feel about working on the game board map presentation in the Vue code of Imperial?

We want to change this:
<img width="1179" alt="Imperial" src="https://user-images.githubusercontent.com/10481391/91058110-15485980-e5f6-11ea-822e-432552f7ecb1.png">
Into this:
![diplomacy_board](https://user-images.githubusercontent.com/10481391/91058186-2abd8380-e5f6-11ea-9597-cbfc00da2e7c.jpg)

The top image is from the `add-rendered-board` branch of this codebase. The bottom image is a photo of the physical gameboard. We don't need to faithfully recreate all the details of the board but getting the various zones (Budapest vs West Balkan vs Ionian Sea, for example) to be visually distinct and appealing is our goal. I imagine that we'd want to attach an `id` for each zone/path in the final board svg so that we can represent units and highlights and such on the zone dynamically. Also, no need to reproduce the rondel in the upper left corner or the Tax/Points chart in the upper right corner.

Some nomenclature:

- `nation` is a country, like France, Austria-Hungary, Germany, Russia, etc.
- `province` is a game space/zone, like Spain, Portugal, Western Mediterranean Sea, etc.
- `player` is a human player of the game, who may control anywhere from 0-6 `nation`s and whose control of those nations changes over the course of a game, depending on the `bond`s they own

Here is an svg from Wikipedia that might be helpful:
https://commons.wikimedia.org/wiki/File:Blank_map_of_Europe_1914.svg

If you have feedback or ideas on how to improve the Vue code (or other code, elsewhere) I am **very** eager to hear about it! I'm also very happy to pair with you on this if you'd like.

**Comment by Thrillberg** [comment]
Here is a copy of the game's instruction book, too, in case that is helpful:
https://web.archive.org/web/20070927080346/http://www.eggertspiele.de/down/imperial/imperial_regel_e.pdf

**Comment by sobelk** [comment]
Are you prioritizing fidelity to the map of Europe or fidelity to the game board? Is the ideal an SVG representation of the game board itself?

**Comment by Thrillberg** [comment]
Great question! I suppose it would depend on the trade-offs, but probably the game board should be seen as authoritative. I only provide the map of Europe in case it is helpful.

**Comment by Thrillberg** [comment]
Resolved by #68
