### ISSUE TITLE
Bug in Asia

### ISSUE THREAD

**Issue by Thrillberg** [Thrillberg/imperial#661]
<img width="1027" alt="Screenshot 2022-12-08 at 7 10 42 PM" src="https://user-images.githubusercontent.com/10481391/206593003-d61f231e-f3e2-4be9-b151-050216563c5c.png">

**Comment by GitGubM8** [comment]
Seems like Asia is working atm, not sure if this ticket is still valid

**Comment by Thrillberg** [comment]
Yeah this is too old and I didn't write anything helpful to repro it so I'll close. Good call.
