### ISSUE TITLE
Remove Cypress

### ISSUE THREAD

**Issue by Thrillberg** [Thrillberg/imperial#686]
It was fun while it lasted 😢

**Comment by GitGubM8** [comment]
What's wrong with it? Isn't it the more unittests the better?

**Comment by Thrillberg** [comment]
Yes, except these are slow and outdated/not maintained. I don't run them with CI so I think they are more cruft than anything else. I'd be open to reviving them if we incorporated it into CI and it didn't slow things down too much. But I feel like that's not really possible. I could be wrong about that, though!

**Comment by Thrillberg** [comment]
So, instead of removing Cypress altogether I think I'll try this out: https://github.com/testdouble/cypress-rails and hopefully revive these tests.

**Comment by Thrillberg** [comment]
I got Cypress back up and running in CI on a branch and it took almost 8 mins to fail on tests: https://github.com/Thrillberg/imperial/actions/runs/4490862844/jobs/7898524932?pr=697

I think we should remove Cypress because it is so slow. The tests are valuable but I'm too impatient to wait this long for each and every build. And if we don't run it in CI then we'll never run it (the current status quo) and we're better off without it. Some of the tests are failing now and I don't know if those failures are legit or not, since things have changed since they were written. What do you think @GitGubM8?

**Comment by GitGubM8** [comment]
Your call, Im not familiar with Cypress at all

For what its worth we already have the other tests too, so keeping Cypress around is redundant
