### ISSUE TITLE
Readjust sizing in Imperial - Tax Status and Bond Purchase

### ISSUE THREAD

**Issue by GitGubM8** [Thrillberg/imperial#692]
## Imperial Only Issue

Right now if a bond purchasing phase is triggered while the Tax Status view is open, they both become kinda squished
![image](https://user-images.githubusercontent.com/28380984/226415225-3f7a8a4c-9976-4074-a18b-3d432331cef9.png)

Showing the available bonds and the Tax Status is fine however
![image](https://user-images.githubusercontent.com/28380984/226415352-d4f08dc2-753f-45c4-968e-86fdac6661c6.png)

Probably worth standardizing the looks to be something like the bottom screenshot than the top

**Comment by Thrillberg** [comment]
[With the redesign using Vuetify](https://github.com/Thrillberg/imperial/commit/28556d4d3a2b4e1dcd690c261956888fafd0e706), this is not an issue any longer.
