### ISSUE TITLE
Add AIs

### ISSUE THREAD

**Issue by GitGubM8** [Thrillberg/imperial#698]
# Depends on https://github.com/Thrillberg/imperial/issues/695:

**Comment by Thrillberg** [comment]
@GitGubM8 AIs! Yes! I attempted this once upon a time: https://github.com/Thrillberg/imperial/compare/main...tensorflow

I was able to get random bots up and running pretty easily but any halfway reasonable AI was too tough for me at the time. I would love to see this!

EDIT: Here is where I added the random bots, in case it helps: https://github.com/Thrillberg/imperial/pull/516 I've subsequently removed them.

**Comment by GitGubM8** [comment]
Once it's been refactored a bit, I think I can do a standard heuristic searching AI with different hyperparams, then if we want something more advance we can do some ML

Also low on priority right now since this will take up a lot of time and depends on a lot of things

**Comment by Thrillberg** [comment]
And here's an attempt at a monte carlo implementation. iirc it was VERY slow: https://github.com/Thrillberg/imperial/pull/518/files

**Comment by Thrillberg** [comment]
Closing this. My interest in AI bots has dropped substantially. I guess I'll keep my PRs open but, _sigh_, I don't think this is a real feature we'll be supporting.
