### ISSUE TITLE
FTUE/Tutorial

### ISSUE THREAD

**Issue by GitGubM8** [Thrillberg/imperial#699]
We can probably increase traffic if we add a First TIme User Experience to newly registered users

Just to explain the rules of the games, how to set up a game and so on

Somewhere between Moderate to Low priority I'd expect

**Comment by Thrillberg** [comment]
This is a great idea! Seems somewhat high effort but could be worth it if we can scope it reasonably. I would love to increase traffic since I think (hope!) the platform is pretty stable as far as rules/bugginess goes.

**Comment by GitGubM8** [comment]
Im not familiar with how much validation we do on the backend, but with a higher traffic we also might have to start considering malicious cmds that may result in a broken game

Altho that's pretty far down the line in the future I'd expect

**Comment by Thrillberg** [comment]
The backend does zero validation. But the front end does validation by having a discrete list of `availableActions`. If the action supplied by the client isn't on that list, [it's ignored](https://github.com/Thrillberg/imperial/blob/cf5a559a90e3c5f096e6d82a7202ec0beeb3aade/app/javascript/lib/imperial.js#L85). Also, I don't allow free text entry on the system (except for username, email, and password) so we have less risk of malice that way, too.
