### ISSUE TITLE
Bug in convoying after combat

### ISSUE THREAD

**Issue by GitGubM8** [Thrillberg/imperial#703]
<img width="814" alt="Screenshot 2023-03-21 at 11 38 10 AM" src="https://user-images.githubusercontent.com/10481391/226659003-66c3da91-5288-4dda-b60b-297feb29c271.png">

**Comment by GitGubM8** [comment]
Not always reproducible I think

**Comment by Thrillberg** [comment]
I'll try to reproduce this in a more abstract test case and see if it fails as described.

**Comment by Thrillberg** [comment]
@GitGubM8 It appears we already have a test case for this: https://github.com/Thrillberg/imperial/blob/43d05982a98dfc568bc6ab1d5f79d5a95b38ce5b/app/javascript/lib/imperial.test.js#L3568

Does this test look like it more or less accurately depicts what is happening in this ticket? If so, then I think you're right - this isn't really reproducible and might be too flaky to chase down.

**Comment by Thrillberg** [comment]
I've also cloned the game and am unable to reproduce. It works as expected. Let's reopen if this comes up again.
