### ISSUE TITLE
Able to trade bonds into other nation's bond

### ISSUE THREAD

**Issue by GitGubM8** [Thrillberg/imperial#741]
Here I attempted to trade the EU 3/6 bond to see if there's anything I can upgrade it to

![image](https://user-images.githubusercontent.com/28380984/228681678-2899fe28-b22e-46f2-a080-3803528cc2a9.png), and was offered a US 5/12

**Comment by Thrillberg** [comment]
Eek! I'll look into this tonight. Thanks!
