### ISSUE TITLE
Auto delete discord channels a few days after game over

### ISSUE THREAD

**Issue by GitGubM8** [Thrillberg/imperial#758]
https://discord.com/developers/docs/resources/channel#deleteclose-channel

Honestly I would give this a negative priority if possible. We only need to clear the channels maybe 3 times a year at most

**Comment by Thrillberg** [comment]
@GitGubM8 I'm thinking about working on this. Now that we have a few more games going at a time, it would be better to keep the channels cleaner than I've bene able to do on my own.

**Comment by Thrillberg** [comment]
We could also delete messages after another "it's your turn" message supersedes the prior one.
