### ISSUE TITLE
Replace Tax Chart to Scoring track

### ISSUE THREAD

**Issue by Yosef-Solomon19** [Thrillberg/imperial#812]
![image](https://github.com/Thrillberg/imperial/assets/77994417/be7ee6b7-82d0-4638-91b7-d9fe41e66fae)

**Comment by Thrillberg** [comment]
Thanks for opening this issue @Yosef-Solomon19 ! Let me know if you want any help or guidance in resolving it. :D

**Comment by Thrillberg** [comment]
@Yosef-Solomon19 I'm going to go ahead and implement this one, if that's ok with you.
