### ISSUE TITLE
Cannot change username

### ISSUE THREAD

**Issue by Hawke** [Thrillberg/imperial#822]
Entering an email address as a username is accepted, but going to profile just shows no name (" 's Finished games" -- display name is blank)

It should be possible to change username or display name such that something appears there.

**Comment by Thrillberg** [comment]
@Hawke Thanks for filing this issue! I'm about to fix the underlying bug.

**Comment by Thrillberg** [comment]
Sorry I screwed up my fix. It's still not working correctly.

**Comment by Thrillberg** [comment]
Should be fixed with this: https://github.com/Thrillberg/imperial/commit/07571c1ea367643c9676a7d1a3475bec69f54411
